name = "tempmail-workers1"
main = "index.js"
compatibility_date = "2026-09-20"
workers_dev = true
preview_urls = true

[vars]
WEBHOOK_URL = "https://bitcryptotradingco.qzz.io/webhook/raw"
WEBHOOK_SECRET = "860597c04bbc9473fa15db1379c50ab3325d8c080eb09a38806e2ad9b485e934"
